version: '3.8'
services:
  env:
    tty: true
    container_name: env_for_python
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/workspace
    ports:
      - 7777:8888
